services:
  next:
    image: ghcr.io/clean-way/cesi-project/next-app:main
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.next-prod.rule=Host(`cleanway.app`)"
      - "traefik.http.routers.next-prod.entrypoints=websecure"
      - "traefik.http.routers.next-prod.tls.certresolver=myresolver"
      - "traefik.http.services.next-prod.loadbalancer.server.port=3000"
      - "traefik.docker.network=internet"
    networks:
      - internet
      - prod
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
networks:
  internet:
    external: true
    name: custom_frontend
  prod: