services:
  next:
    image: ghcr.io/clean-way/cesi-project/next-app:develop
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
      APPLE_CLIENT_SECRET: $APPLE_CLIENT_SECRET
      APPLE_TEAM_ID: $APPLE_TEAM_ID
      APPLE_CLIENT_ID: $APPLE_CLIENT_ID
      APPLE_PRIVATE_KEY: $APPLE_PRIVATE_KEY
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      NEXTAUTH_SECRET: $NEXTAUTH_SECRET
      NEXTAUTH_URL: $DEV_NEXTAUTH_URL
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.next-dev.rule=Host(`dev.cleanway.app`)"
      - "traefik.http.routers.next-dev.entrypoints=websecure"
      - "traefik.http.routers.next-dev.tls.certresolver=myresolver"
      - "traefik.http.services.next-dev.loadbalancer.server.port=3000"
      - "traefik.docker.network=internet"
    networks:
      - internet
      - dev
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - dev

volumes:
  postgres:

networks:
  internet:
    external: true
    name: custom_frontend
  dev: