name: build
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:    
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run tests
      run: npm run test
  
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run Unit Test
      run: npm run test

  cypress:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install modules
      run: npm ci

    - name: Migrade DB
      run: psql -h localhost -p 5432 -U postgres -d postgres < cypress/test.sql
      env:
        PGPASSWORD: postgres

    - name : Cypress run
      uses: cypress-io/github-action@v2
      env:
        NEXTAUTH_SECRET: "test"
      with:
        build: npm run build
        start: npm run start
        config-file: cypress.config.ts
        browser: chrome
        record: true
      uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          
  build-prod:
    runs-on: ubuntu-latest
    needs: [eslint, tests, cypress]
    if: github.ref_name == 'main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/next-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: | 
            NEXT_PUBLIC_NEXTAPI_URL=${{ secrets.PROD_NEXT_PUBLIC_NEXTAPI_URL }}
            NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.PROD_NEXT_PUBLIC_MAPBOX_TOKEN }}
            GOOGLE_KEYFILE=${{ secrets.GOOGLE_KEYFILE }}

  build-dev:
      runs-on: ubuntu-latest
      needs: [eslint, tests, cypress]
      if: github.ref_name == 'develop'
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/next-app

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            target: development
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              NEXT_PUBLIC_NEXTAPI_URL=${{ secrets.DEV_NEXT_PUBLIC_NEXTAPI_URL }}
              NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.DEV_NEXT_PUBLIC_MAPBOX_TOKEN }}
              GOOGLE_KEYFILE=${{ secrets.GOOGLE_KEYFILE }}
