name: build
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:    
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint
          
  build-prod:
    runs-on: ubuntu-latest
    needs: [eslint]
    if: github.ref_name == 'main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/next-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: | 
            NEXT_PUBLIC_NEXTAPI_URL=${{ secrets.PROD_NEXT_PUBLIC_NEXTAPI_URL }}
            NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.PROD_NEXT_PUBLIC_MAPBOX_TOKEN }}

  build-dev:
      runs-on: ubuntu-latest
      needs: [eslint]
      if: github.ref_name == 'develop'
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/next-app

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            target: development
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              NEXT_PUBLIC_NEXTAPI_URL=${{ secrets.DEV_NEXT_PUBLIC_NEXTAPI_URL }}
              NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.DEV_NEXT_PUBLIC_MAPBOX_TOKEN }}
            